export interface AnimeType {
  id: string
  title: string
  chineseTitle: string
  description: string
  image: string
  coverImage: string
  rating: number
  releaseDate: string
  episodes: number
  status: string
  categories: string[]
  featured: boolean
  popular: boolean
  director: string
  studio: string
  originalWork: string
}

export const animeData: AnimeType[] = [
  {
    id: "1",
    title: "The Legend of Sword Domain",
    chineseTitle: "剑域风云",
    description:
      "在一个充满魔法和武术的世界里，年轻的剑客李云踏上了寻找传说中的神剑之旅，以拯救他的家乡免受邪恶势力的侵害。在旅途中，他结识了各种各样的伙伴，学习了强大的剑术，并发现了关于自己身世的秘密。",
    image: "/placeholder.svg?height=450&width=300",
    coverImage: "/placeholder.svg?height=900&width=1600",
    rating: 9.2,
    releaseDate: "2024-01-15",
    episodes: 24,
    status: "连载中",
    categories: ["武侠", "奇幻", "冒险"],
    featured: true,
    popular: true,
    director: "张伟",
    studio: "天空动画",
    originalWork: "小说《剑域》",
  },
  {
    id: "2",
    title: "Immortal Cultivation Journey",
    chineseTitle: "修仙之路",
    description:
      "平凡少年王小凡意外获得了上古修仙功法，从此踏上了修仙之路。在这个充满仙侠元素的世界里，他经历了无数磨难，结交了志同道合的朋友，对抗各种强大的敌人，逐渐成长为一代仙尊。",
    image: "/placeholder.svg?height=450&width=300",
    coverImage: "/placeholder.svg?height=900&width=1600",
    rating: 9.5,
    releaseDate: "2023-11-20",
    episodes: 36,
    status: "连载中",
    categories: ["仙侠", "修真", "奇幻"],
    featured: true,
    popular: true,
    director: "李明",
    studio: "仙境工作室",
    originalWork: "网络小说《修仙之路》",
  },
  {
    id: "3",
    title: "The Great Mage Returns",
    chineseTitle: "大法师归来",
    description:
      "曾经的大法师陈长生在沉睡千年后苏醒，发现世界已经发生了翻天覆地的变化。他必须适应新的魔法体系，同时应对古老敌人的威胁。在这个过程中，他重新找回了自己的力量，并揭开了自己沉睡的真相。",
    image: "/placeholder.svg?height=450&width=300",
    coverImage: "/placeholder.svg?height=900&width=1600",
    rating: 8.9,
    releaseDate: "2023-09-05",
    episodes: 12,
    status: "完结",
    categories: ["玄幻", "魔法", "冒险"],
    featured: false,
    popular: true,
    director: "赵强",
    studio: "魔法石动画",
    originalWork: "原创",
  },
  {
    id: "4",
    title: "Cyber Shanghai 2088",
    chineseTitle: "赛博上海2088",
    description:
      "2088年的上海，科技高度发达，人工智能与人类共存。女主角林小雨是一名网络安全专家，她发现了一个可能颠覆整个社会的阴谋。在调查过程中，她不得不与各种高科技犯罪作斗争，同时质疑自己的身份和记忆。",
    image: "/placeholder.svg?height=450&width=300",
    coverImage: "/placeholder.svg?height=900&width=1600",
    rating: 9.0,
    releaseDate: "2024-02-28",
    episodes: 18,
    status: "连载中",
    categories: ["科幻", "赛博朋克", "悬疑"],
    featured: true,
    popular: false,
    director: "陈晓",
    studio: "未来视觉",
    originalWork: "原创",
  },
  {
    id: "5",
    title: "Three Kingdoms: New Era",
    chineseTitle: "三国新纪元",
    description:
      "这是一部对中国古典名著《三国演义》的现代改编。故事设定在一个架空的历史世界，三国时期的英雄们使用了奇幻的武器和能力。刘备、关羽、张飞等经典角色以全新的面貌出现，演绎了一段不同于历史的传奇。",
    image: "/placeholder.svg?height=450&width=300",
    coverImage: "/placeholder.svg?height=900&width=1600",
    rating: 8.7,
    releaseDate: "2023-07-10",
    episodes: 40,
    status: "完结",
    categories: ["历史", "奇幻", "战争"],
    featured: false,
    popular: true,
    director: "王刚",
    studio: "历史长河动画",
    originalWork: "改编自《三国演义》",
  },
  {
    id: "6",
    title: "Spirit Beast Master",
    chineseTitle: "灵兽师",
    description:
      "在一个人类可以与灵兽缔结契约的世界里，少年林轩意外与一只传说中的上古灵兽结成契约。这只灵兽拥有强大但难以控制的力量，林轩必须学会如何与它相处，同时参加灵兽师的选拔赛，成为一名真正的灵兽师。",
    image: "/placeholder.svg?height=450&width=300",
    coverImage: "/placeholder.svg?height=900&width=1600",
    rating: 8.8,
    releaseDate: "2023-12-05",
    episodes: 24,
    status: "连载中",
    categories: ["奇幻", "冒险", "少年"],
    featured: true,
    popular: false,
    director: "刘芳",
    studio: "奇幻世界",
    originalWork: "漫画《灵兽师》",
  },
  {
    id: "7",
    title: "The Last Immortal",
    chineseTitle: "最后的仙人",
    description:
      "仙界大战后，仙人几乎灭绝，只剩下主角一人在人间界生活。他隐藏身份，过着平凡的生活，但随着一系列超自然事件的发生，他不得不重新拿起法宝，对抗入侵人间的妖魔，同时寻找是否还有其他幸存的仙人。",
    image: "/placeholder.svg?height=450&width=300",
    coverImage: "/placeholder.svg?height=900&width=1600",
    rating: 9.3,
    releaseDate: "2024-03-01",
    episodes: 12,
    status: "连载中",
    categories: ["仙侠", "奇幻", "动作"],
    featured: false,
    popular: true,
    director: "杨光",
    studio: "仙光动画",
    originalWork: "原创",
  },
  {
    id: "8",
    title: "Dragon City Chronicles",
    chineseTitle: "龙城纪",
    description:
      "在一个人类与龙共存的城市里，主角陈龙是一名龙语者，能够与龙沟通。当一系列针对龙的神秘袭击事件发生时，他与女警官李雪一起调查，揭开了一个关于龙族起源的惊天秘密，同时也发现了自己身世之谜。",
    image: "/placeholder.svg?height=450&width=300",
    coverImage: "/placeholder.svg?height=900&width=1600",
    rating: 8.5,
    releaseDate: "2023-10-15",
    episodes: 24,
    status: "完结",
    categories: ["奇幻", "悬疑", "冒险"],
    featured: false,
    popular: false,
    director: "龙天",
    studio: "龙腾动画",
    originalWork: "小说《龙城》",
  },
  {
    id: "9",
    title: "Martial Arts Academy",
    chineseTitle: "武道学院",
    description:
      "在一个武道昌盛的现代世界，各国设立了武道学院培养武道天才。主角林风因为特殊体质被武道学院破格录取，在学院中他不断挑战自我，结交朋友，参加各种武道比赛，逐渐成长为一代武道大师。",
    image: "/placeholder.svg?height=450&width=300",
    coverImage: "/placeholder.svg?height=900&width=1600",
    rating: 8.6,
    releaseDate: "2023-08-20",
    episodes: 36,
    status: "完结",
    categories: ["武侠", "校园", "热血"],
    featured: false,
    popular: true,
    director: "武天",
    studio: "武道天下",
    originalWork: "漫画《武道学院》",
  },
  {
    id: "10",
    title: "Time Walker",
    chineseTitle: "时间行者",
    description:
      "科学家张明发明了时间穿梭装置，但在一次实验中，他被意外送到了未来世界。在那里，他发现人类文明已经衰落，地球环境恶化。他决定找出导致这一切的原因，并试图改变未来，同时寻找回到自己时代的方法。",
    image: "/placeholder.svg?height=450&width=300",
    coverImage: "/placeholder.svg?height=900&width=1600",
    rating: 9.1,
    releaseDate: "2024-01-05",
    episodes: 16,
    status: "连载中",
    categories: ["科幻", "时空", "冒险"],
    featured: true,
    popular: false,
    director: "时光",
    studio: "时空工作室",
    originalWork: "原创",
  },
  {
    id: "11",
    title: "The Ancient Scroll",
    chineseTitle: "远古卷轴",
    description:
      "考古学家李明在一次发掘中发现了一卷神秘的古代卷轴，打开后他获得了看到过去的能力。通过这种能力，他揭开了许多历史之谜，但同时也引来了一个神秘组织的追杀，他们想要利用卷轴的力量改变历史。",
    image: "/placeholder.svg?height=450&width=300",
    coverImage: "/placeholder.svg?height=900&width=1600",
    rating: 8.4,
    releaseDate: "2023-06-10",
    episodes: 20,
    status: "完结",
    categories: ["历史", "悬疑", "冒险"],
    featured: false,
    popular: false,
    director: "古风",
    studio: "远古动画",
    originalWork: "小说《卷轴》",
  },
  {
    id: "12",
    title: "Demon Hunter Academy",
    chineseTitle: "猎魔学院",
    description:
      "在一个妖魔鬼怪与人类共存的世界，猎魔人是维持秩序的关键。主角赵小虎是猎魔学院的一名学生，虽然天赋平平，但通过努力和坚持，他逐渐成长，最终成为了一名优秀的猎魔人，并揭露了学院背后的秘密。",
    image: "/placeholder.svg?height=450&width=300",
    coverImage: "/placeholder.svg?height=900&width=1600",
    rating: 8.9,
    releaseDate: "2023-11-01",
    episodes: 24,
    status: "连载中",
    categories: ["奇幻", "校园", "动作"],
    featured: false,
    popular: true,
    director: "魔猎",
    studio: "猎魔工作室",
    originalWork: "漫画《猎魔学院》",
  },
  {
    id: "13",
    title: "The Forgotten Kingdom",
    chineseTitle: "被遗忘的王国",
    description:
      "在一个被遗忘的古代王国遗迹中，考古队发现了沉睡的公主。她醒来后发现自己的王国已经消失千年，而她体内蕴含的神秘力量引来了各方势力的觊觎。一个普通大学生意外卷入其中，成为了保护公主的关键人物。",
    image: "/placeholder.svg?height=450&width=300",
    coverImage: "/placeholder.svg?height=900&width=1600",
    rating: 8.7,
    releaseDate: "2023-09-15",
    episodes: 16,
    status: "完结",
    categories: ["奇幻", "历史", "爱情"],
    featured: false,
    popular: false,
    director: "王国",
    studio: "遗忘动画",
    originalWork: "原创",
  },
  {
    id: "14",
    title: "Cosmic Wanderer",
    chineseTitle: "宇宙流浪者",
    description:
      "在未来世界，人类已经开始星际移民。宇航员张星因为一次意外，与自己的智能宇宙飞船一起被传送到了宇宙的未知区域。他们必须在这片充满危险的宇宙中生存，寻找回家的路，同时探索宇宙的奥秘。",
    image: "/placeholder.svg?height=450&width=300",
    coverImage: "/placeholder.svg?height=900&width=1600",
    rating: 9.0,
    releaseDate: "2024-02-15",
    episodes: 12,
    status: "连载中",
    categories: ["科幻", "太空", "冒险"],
    featured: true,
    popular: false,
    director: "星辰",
    studio: "宇宙工作室",
    originalWork: "小说《流浪者》",
  },
  {
    id: "15",
    title: "The Divine Chef",
    chineseTitle: "神厨",
    description:
      "主角李小厨是一名普通厨师，某天他意外获得了一本神秘的食谱，可以做出具有神奇效果的料理。他用这些料理帮助了很多人，同时也引来了美食界的关注和竞争。在这个过程中，他不断提升厨艺，探索食谱的秘密。",
    image: "/placeholder.svg?height=450&width=300",
    coverImage: "/placeholder.svg?height=900&width=1600",
    rating: 8.8,
    releaseDate: "2023-10-10",
    episodes: 24,
    status: "完结",
    categories: ["美食", "奇幻", "日常"],
    featured: false,
    popular: true,
    director: "美食家",
    studio: "食神动画",
    originalWork: "漫画《神厨》",
  },
  {
    id: "16",
    title: "Virtual World Online",
    chineseTitle: "虚拟世界在线",
    description:
      "2030年，全息虚拟现实游戏《虚拟世界》风靡全球。主角陈风是游戏中的顶尖玩家，某天他发现游戏中出现了不属于程序设定的异常现象。随着调查深入，他发现游戏与现实世界之间的界限正在模糊，两个世界的命运都掌握在他手中。",
    image: "/placeholder.svg?height=450&width=300",
    coverImage: "/placeholder.svg?height=900&width=1600",
    rating: 9.4,
    releaseDate: "2024-03-10",
    episodes: 24,
    status: "连载中",
    categories: ["科幻", "游戏", "冒险"],
    featured: true,
    popular: true,
    director: "游戏王",
    studio: "虚拟现实",
    originalWork: "小说《虚拟世界》",
  },
]
